#!/usr/bin/env bash
# Script that installs nginx on a server and sets up a html
# page that prints hello world by default
sudo apt -y install nginx
mkdir -p /etc/nginx/html
echo "Hello World!" >/etc/nginx/html/index.html
printf %s "server{
  listen 80 default_server;
  listen [::]:80 default_server;
  root   /etc/nginx/html;
  index  index.html index.htm;
}" >/etc/nginx/sites-available/default
service nginx restart
