#!/usr/bin/env bash
# Script that configures Nginx server so that /redirect_me
# is redirecting to another page

sudo apt -y install nginx
mkdir -p /etc/nginx/html
echo "Hello World!" >/etc/nginx/html/index.html
printf %s "server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root   /etc/nginx/html;
  index  index.html index.htm;

  location /redirect_me {
        return 301 https://www.google.com/;
    }
}" >/etc/nginx/sites-available/default
service nginx restart
