#!/usr/bin/env bash
# Script that configures Nginx server so that /redirect_me
# is redirecting to another page

sudo apt -y install nginx
mkdir -p /etc/nginx/html
echo "Hello World!" >/etc/nginx/html/index.html
echo "Ceci n'est pas une page" >/etc/nginx/html/404.html
printf %s "server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root   /etc/nginx/html;
  index  index.html index.htm;

  location /redirect_me {
        return 301 https://www.google.com/;
  }

  error_page 404 /404.html;
  location = /404.html {
    root /etc/nginx/html;
    internal;
  }
}" >/etc/nginx/sites-available/default
service nginx restart
