#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a
# custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install Nginx

# Configure firewall
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html /var/www/error

# Permissions to allow file creation
sudo chmod -R 755 /var/www
echo 'Hello World' >/var/www/html/index.html
echo "Ceci n'est pas une page" >/var/www/html/404.html

# Configuration settings string
configuration="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://youtube.com permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"

# Restart the nginx service
echo "$configuration" >/etc/nginx/sites-enabled/default
sudo service nginx restart
