#!/usr/bin/env bash
# Install and configure HAproxy on loab-balancer server.
sudo apt-get -y update
sudo apt-get -y install haproxy

#Configuration
configuration="
frontend http-in
  bind *:80
  mode http
  default_backend servers
backend servers
  balance roundrobin
  server 510384-web-01 35.153.93.227:80 check
  # server 510384-web-02 54.198.77.248:80 check
  server 510384-web-02 100.26.175.131:80 check
"
echo "$configuration" | sudo tee -a /etc/haproxy/haproxy.cfg

#Enabling haproxy and restarting
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart

100.26.175.131
