#!/usr/bin/env bash
# A shell based implimitation of the Fizzbuzz interview question.

for number in {1..100}
do
  if (( number % 3 == 0 && num % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( number % 3 == 0 ))
  then
    echo "Fizz"
  elif (( number % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$number"
  fi
done
