#!/usr/bin/env bash
# Prints a bunch of text using a while loop and if condition

counter=0

while [ $counter -lt 10 ]
do
  if [ $counter -eq 3 ]
  then
    echo "bad luck"
  elif [ $counter -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( counter++ ))
done
